version: '3.8'
services:
  service-a:
    build: ./service-a
    ports:
      - "8001:8000"
    environment:
      - SERVICE_B_URL=http://service-b:8000
    depends_on:
      - service-b

  service-b:
    build: ./service-b
    ports:
      - "8002:8000"
