name: Deploy Two-Container App

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: prototype01-rg
  CONTAINER_ENV: prototype-env
  LOCATION: westeurope
  GHCR_REGISTRY: ghcr.io
  GHCR_USER: ${{ github.repository_owner }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ env.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ env.GHCR_USER }} --password-stdin

    - name: Build and push service-a
      run: |
        docker build -t ghcr.io/${{ env.GHCR_USER }}/service-a:latest ./service-a
        docker push ghcr.io/${{ env.GHCR_USER }}/service-a:latest

    - name: Build and push service-b
      run: |
        docker build -t ghcr.io/${{ env.GHCR_USER }}/service-b:latest ./service-b
        docker push ghcr.io/${{ env.GHCR_USER }}/service-b:latest

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create or update Service B with revision label
      run: |
        az containerapp create \
          --name service-b \
          --resource-group $RESOURCE_GROUP \
          --environment $CONTAINER_ENV \
          --image ghcr.io/${{ env.GHCR_USER }}/service-b:latest \
          --target-port 8000 \
          --ingress external \
          --registry-server ghcr.io \
          --registry-username ${{ env.GHCR_USER }} \
          --registry-password ${{ env.GHCR_TOKEN }} \
          --revision-suffix b-${{ github.run_number }} \
          --min-replicas 0 \
          --max-replicas 1 \
          --cpu 0.25 \
          --memory 0.5Gi || \
        az containerapp update \
          --name service-b \
          --resource-group $RESOURCE_GROUP \
          --image ghcr.io/${{ env.GHCR_USER }}/service-b:latest \
          --revision-suffix b-${{ github.run_number }} \
          --cpu 0.25 \
          --memory 0.5Gi

    - name: Get Service B FQDN
      id: service-b-fqdn
      run: |
        fqdn=$(az containerapp show --name service-b --resource-group $RESOURCE_GROUP --query "properties.configuration.ingress.fqdn" -o tsv)
        echo "SERVICE_B_URL=http://$fqdn" >> $GITHUB_ENV

    - name: Create or update Service A with revision label
      run: |
        az containerapp create \
          --name service-a \
          --resource-group $RESOURCE_GROUP \
          --environment $CONTAINER_ENV \
          --image ghcr.io/${{ env.GHCR_USER }}/service-a:latest \
          --target-port 8000 \
          --ingress external \
          --env-vars SERVICE_B_URL=${{ env.SERVICE_B_URL }} \
          --registry-server ghcr.io \
          --registry-username ${{ env.GHCR_USER }} \
          --registry-password ${{ env.GHCR_TOKEN }} \
          --revision-suffix a-${{ github.run_number }} \
          --min-replicas 0 \
          --max-replicas 1 \
          --cpu 0.25 \
          --memory 0.5Gi || \
        az containerapp update \
          --name service-a \
          --resource-group $RESOURCE_GROUP \
          --image ghcr.io/${{ env.GHCR_USER }}/service-a:latest \
          --revision-suffix a-${{ github.run_number }} \
          --cpu 0.25 \
          --memory 0.5Gi
